/**
 * Klubdata — ret navne, kampe og tekster her.
 * Offentlige sider viser kun navne. Numre og licenser vises i medlemsportalen.
 */
window.LLC_DATA = {
  coaches: [
    { name: "Olsen", role: "SoMe" },
    { name: "Værnet & Souary", role: "Bødlerne" },
    { name: "Daae", role: "Fitness" },
  ],

  squad: [
    { name: "Souary", pos: "Målmand", number: 1, license: "6", since: 2016 },
    { name: "Rost", pos: "Wing Back", number: 13, license: "1", since: 2016 },
    { name: "Fønss", pos: "Forsvar", number: 77, license: "3", since: 2016, captain: true },
    { name: "Bisgaard", pos: "Midtbane", number: 6, license: "4", since: 2016 },
    { name: "Værnet", pos: "Angreb", number: 9, license: "10", since: 2016 },
    { name: "Daae", pos: "Wing Back", number: 7, license: "5", since: 2016 },
    { name: "Hammerum", pos: "Midtbane", number: 24, license: "7", since: 2016 },
    { name: "Olsen", pos: "Angreb", number: 11, license: "13", since: 2016 },
    { name: "Zeko", pos: "Midtbane", number: 5, license: "11", since: 2016 },
    { name: "Balthzer", pos: "Angreb", number: 12, license: "25", since: 2020 },
    { name: "Mikkelsen", pos: "Forsvar", number: 52, license: "26", since: 2022 },
    { name: "Prip", pos: "Midtbane", number: 8, license: "28", since: 2022 },
    { name: "Rostrup", pos: "Midtbane", number: 14, license: "31", since: 2024 },
    { name: "Poulsen", pos: "Angreb", number: 39, license: "32", since: 2024 },
    { name: "Lium", pos: "Midtbane", number: 46, license: "30", since: 2024 },
    { name: "Ropstad", pos: "Angreb", number: 17, license: "33", since: 2026 },
  ],

  awardsLatest: [
    { title: "Årets spiller", name: "Zaki" },
    { title: "Årets fighter", name: "Bisgaard" },
    { title: "Årets mål", name: "Verner" },
    { title: "Årets afbrænder", name: "Zeko" },
    { title: "Årets jubelscene", name: "Anders" },
    { title: "Årets keeper", name: "Zaki" },
    { title: "Årets assist", name: "Bisgaard" },
    { title: "Årets plæneklipper", name: "Rost" },
    { title: "Årets åbenbaring", name: "P" },
    { title: "Årets Lars", name: "Jakob" },
    { title: "Årets topscorer", name: "Jakob" },
  ],

  hallOfFame: [
    {
      year: "2016",
      title: "Stifterne",
      text: "Tolv venner, ét lokomotiv og en kold dag i december. Klubben blev stiftet 9. december 2016 og har skovlet kul lige siden.",
    },
    {
      year: "2018",
      title: "Første puljeskift",
      text: "Oprykning i C-rækken. Blå trøje, hvide bukser — klasikeren.",
    },
    {
      year: "2021",
      title: "7–2 over FC Skumtoget",
      text: "Sæsonens brag i Valby Idrætspark. Et resultat der stadig bliver nævnt, når der skal mindes om, at toget kan køre.",
    },
    {
      year: "2018",
      title: "Første Award Show",
      text: "Galla i sort og rødt. Årets Spiller, Mål, Assist og Lars blev uddelt under røde lamper.",
    },
    {
      year: "2025",
      title: "Award Show",
      text: "Rekordmange omstemninger. Årets spiller: Zaki. Årets Lars og topscorer: Jakob. Årets fighter og assist: Bisgaard.",
    },
    {
      year: "2026",
      title: "De stribede",
      text: "Nye spillertrøjer i rød og sort lodret stribe. Jernbane-DNA på ærmet. Banen er den samme. Toget har skiftet spor.",
    },
  ],

  kits: [
    { id: "whiteblue", name: "Den blå og hvide", years: "2016–", shirt: "Navy / hvid chevron", shorts: "Hvid", note: "Klasikeren. Nike, V-stribe.", photo: "assets/img/kits/bluewhite.jpg" },
    { id: "yellow", name: "Den gule", years: "2016–2022", shirt: "Gul / blå ternet", shorts: "Hvid", note: "Synlig i efterårsmørket.", photo: "assets/img/kits/yellow.jpg" },
    { id: "redblue", name: "Den røde og blå", years: "2022–2026", shirt: "Navy / rød", shorts: "Hvid", note: "Joma. Trøje Gate 6.7.", photo: "assets/img/kits/redblue.jpg" },
    { id: "blue", name: "Den blå", years: "2022–2026", shirt: "Navy pinstripe", shorts: "Navy", note: "Joma. Bauhaus i ryggen.", photo: "assets/img/kits/blue.jpg" },
    { id: "current", name: "Striberne", years: "2026–", shirt: "Rød/sort stribe, Hummel", shorts: "Sort", note: "Nuværende. Holdsport på brystet.", photo: "assets/img/kits/current.jpg" },
  ],

  fixtures: [
    { season: "forar", round: 1, date: "2026-04-10", time: "17:30", home: true, opponent: "Stribberne", venue: "Valby Idrætspark 7, Kunst 41", result: "4–3" },
    { season: "forar", round: 3, date: "2026-04-26", time: "10:00", home: true, opponent: "FC Sailing Lads", venue: "Valby Idrætspark 7, Kunst 40", result: null, note: "UHT" },
    { season: "forar", round: 4, date: "2026-05-04", time: "20:30", home: false, opponent: "FBK", venue: "Kløvermarken 7, Kunst 42", result: "2–0" },
    { season: "forar", round: 5, date: "2026-05-10", time: "12:20", home: true, opponent: "Absalons Boldklub af 2012", venue: "Valby Idrætspark 7, Kunst 41", result: "4–2" },
    { season: "forar", round: 6, date: "2026-05-16", time: "11:10", home: false, opponent: "A-holdet", venue: "Kløvermarken 7, Kunst 43", result: "4–4" },
    { season: "forar", round: 7, date: "2026-05-23", time: "12:00", home: true, opponent: "Valby Fulbo 1.", venue: "Valby Idrætspark 7, Kunst 41", result: "1–3" },
    { season: "forar", round: 8, date: "2026-05-31", time: "10:00", home: false, opponent: "Svaneke Boldklub", venue: "Valby Idrætspark 7, Kunst 42", result: "1–2" },
    { season: "forar", round: 10, date: "2026-06-14", time: "11:10", home: false, opponent: "Stribberne", venue: "Valby Idrætspark 7, Kunst 40", result: "0–3" },
    { season: "forar", round: 11, date: "2026-06-19", time: "17:30", home: true, opponent: "Skurvognen FC", venue: "Valby Idrætspark 7, Kunst 41", result: "0–3", note: "HHT" },
    { season: "forar", round: 2, date: "2026-06-26", time: "18:40", home: false, opponent: "Skurvognen FC", venue: "Valby Idrætspark 7, Kunst 40", result: "1–3" },
    { season: "efterar", round: 12, date: "2026-08-16", time: "12:20", home: false, opponent: "FC Sailing Lads", venue: "Udgået", result: null, cancelled: true, note: "Hold trukket" },
    { season: "efterar", round: 13, date: "2026-08-25", time: "21:00", home: true, opponent: "FBK", venue: "Valby Idrætspark 7, Kunst 40", result: null },
    { season: "efterar", round: 14, date: "2026-08-29", time: "12:00", home: false, opponent: "Absalons Boldklub af 2012", venue: "Valby Idrætspark 7, Kunst 40", result: null },
    { season: "efterar", round: 16, date: "2026-09-12", time: "12:00", home: false, opponent: "Valby Fulbo 1.", venue: "Valby Idrætspark 7, Kunst 40", result: null },
    { season: "efterar", round: 17, date: "2026-09-19", time: "13:10", home: true, opponent: "Svaneke Boldklub", venue: "Valby Idrætspark 7, Kunst 42", result: null },
    { season: "efterar", round: 18, date: "2026-09-27", time: "12:20", home: false, opponent: "UD Retiraos", venue: "Valby Idrætspark 7, Kunst 43", result: null },
    { season: "efterar", round: 9, date: "2026-09-30", time: "17:30", home: true, opponent: "UD Retiraos", venue: "Valby Idrætspark 7, Kunst 40", result: null },
    { season: "efterar", round: 15, date: "2026-10-04", time: "11:10", home: true, opponent: "A-holdet", venue: "Valby Idrætspark 7, Kunst 42", result: null },
  ],

  table: [
    { pos: 1, team: "Valby Fulbo 1.", p: 12, w: 8, d: 2, l: 2, gf: 34, ga: 15, pts: 26 },
    { pos: 2, team: "A-holdet", p: 12, w: 8, d: 1, l: 3, gf: 47, ga: 37, pts: 25 },
    { pos: 3, team: "Lokomotiv LarsbertoCarlos", p: 9, w: 5, d: 1, l: 3, gf: 21, ga: 19, pts: 16 },
    { pos: 4, team: "Stribberne", p: 11, w: 4, d: 2, l: 5, gf: 33, ga: 34, pts: 14 },
    { pos: 5, team: "Skurvognen FC", p: 12, w: 4, d: 1, l: 7, gf: 24, ga: 36, pts: 13 },
    { pos: 6, team: "Svaneke Boldklub", p: 10, w: 4, d: 0, l: 6, gf: 23, ga: 29, pts: 12 },
    { pos: 7, team: "FBK", p: 9, w: 3, d: 2, l: 4, gf: 34, ga: 26, pts: 11 },
    { pos: 8, team: "UD Retiraos", p: 7, w: 3, d: 2, l: 2, gf: 16, ga: 12, pts: 11 },
    { pos: 9, team: "Absalons Boldklub af 2012", p: 10, w: 1, d: 1, l: 8, gf: 20, ga: 44, pts: 4 },
    { pos: 10, team: "FC Sailing Lads", p: 0, w: 0, d: 0, l: 0, gf: 0, ga: 0, pts: 0 },
  ],

  events: [
    { date: "2026-08-25", time: "21:00", title: "Kamp: FBK", place: "Valby Idrætspark 7, Kunst 40", kind: "kamp" },
    { date: "2026-08-29", time: "12:00", title: "Kamp: Absalons Boldklub af 2012", place: "Valby Idrætspark 7, Kunst 40", kind: "kamp" },
    { date: "2026-09-12", time: "12:00", title: "Kamp: Valby Fulbo 1.", place: "Valby Idrætspark 7, Kunst 40", kind: "kamp" },
    { date: "2026-09-12", time: "19:00", title: "Generalforsamling", place: "Klubhuset", kind: "møde" },
    { date: "2026-09-19", time: "13:10", title: "Kamp: Svaneke Boldklub", place: "Valby Idrætspark 7, Kunst 42", kind: "kamp" },
    { date: "2026-09-27", time: "12:20", title: "Kamp: UD Retiraos", place: "Valby Idrætspark 7, Kunst 43", kind: "kamp" },
    { date: "2026-09-30", time: "17:30", title: "Kamp: UD Retiraos", place: "Valby Idrætspark 7, Kunst 40", kind: "kamp" },
    { date: "2026-10-04", time: "11:10", title: "Kamp: A-holdet", place: "Valby Idrætspark 7, Kunst 42", kind: "kamp" },
    { date: "2026-11-21", time: "18:30", title: "Award Show 2026", place: "Valby, hemmelig adresse følger", kind: "event" },
    { date: "2026-12-09", time: "19:00", title: "10 års jubilæum", place: "Valby", kind: "event" },
  ],

  instagram: [
    {
      date: "14. aug 2022",
      caption: "Målfest i Valby. Jakob, Bis, Balthzer, Rost og OK. Kampen ender 10–4. Husk at drikke vand.",
      url: "https://www.instagram.com/p/ChQIpBwMpZZ/",
      opponent: "KBH Vendsyssel",
      result: "10–4",
      tone: "kamp",
    },
    {
      date: "13. sep 2022",
      caption: "OK tre mål, Fønss to — lobben over målmanden. Verner og Balthzer. Tempo 7–2. BauhausMoM: Anders.",
      url: "https://www.instagram.com/p/CicCJaEsFa6/",
      opponent: "Tempo",
      result: "7–2",
      tone: "kamp",
    },
    {
      date: "10. apr 2026",
      caption: "Sæsonåbning. Stribberne 4–3 på Kunst 41. Toget kører.",
      url: "https://www.instagram.com/larsbertocarlos/",
      opponent: "Stribberne",
      result: "4–3",
      tone: "kamp",
    },
    {
      date: "10. maj 2026",
      caption: "Absalons Boldklub 4–2 hjemme. Tre point i 7. B., B-3.",
      url: "https://www.instagram.com/larsbertocarlos/",
      opponent: "Absalon",
      result: "4–2",
      tone: "kamp",
    },
    {
      date: "15. jun 2026",
      caption: "Ti små larsbertoer. Clean sheet, tre mål, GOAT assist. Balthzer hev den hjem.",
      url: "https://www.instagram.com/p/DZoncC3N8KH/",
      opponent: "Stribberne",
      result: "3–0",
      tone: "kamp",
    },
    {
      date: "15. jun 2019",
      caption: "Regndans mod Cph. Celtic. Oskar solo, Zeko, Abdi. 3–1 og MOTM til Oskar.",
      url: "https://www.instagram.com/p/ByvxyLtBFGR/",
      opponent: "Cph. Celtic",
      result: "3–1",
      tone: "kamp",
    },
  ],

  gallery: [
    {
      title: "Award Show — seneste galla",
      cat: "award",
      year: "2025",
      date: "2025-11-01",
      opponent: "Galla",
      result: null,
      excerpt: "Rekordmange omstemninger og overlæggerafgørelser. Årets spiller: Zaki. Årets Lars og topscorer: Jakob. Årets fighter: Bisgaard. Årets mål: Verner.",
      url: "https://www.instagram.com/p/DRZvgWZDcKD/",
      tags: "#awardshow",
    },
    {
      title: "Målfest: 10–4",
      cat: "kamp",
      year: "2022",
      date: "2022-08-14",
      opponent: "KBH Vendsyssel",
      result: "10–4",
      excerpt: "Årets varmeste dag i Valby Parken. Jakob åbner efter 2 minutter. Bis, Balthzer-solotur, Rost. Anden halvleg åbner op: Jakob, Bis, OK, Rost, Jakob, Bis. 10–4. Husk at drikke vand.",
      url: "https://www.instagram.com/p/ChQIpBwMpZZ/",
      tags: "#chuchu #merekul #llcsæsonen2022",
    },
    {
      title: "Tempo kunne ikke følge med",
      cat: "kamp",
      year: "2022",
      date: "2022-09-13",
      opponent: "Tempo",
      result: "7–2",
      motm: "Anders",
      excerpt: "OK 3, kaptajn Fønss 2 — lobben over målmanden på tværs af feltet. Verner og Balthzer. 7–2, og det kunne være endt værre for Tempo. BauhausMoM: Anders.",
      url: "https://www.instagram.com/p/CicCJaEsFa6/",
      tags: "#chuchu #llcsæsonen2022 #merekul",
    },
    {
      title: "Stribberne 4–3",
      cat: "kamp",
      year: "2026",
      date: "2026-04-10",
      opponent: "Stribberne",
      result: "4–3",
      excerpt: "Sæsonåbning, fredag kl. 17:30, Kunst 41. Syv mål og tre point.",
      url: "https://www.instagram.com/larsbertocarlos/",
      tags: "#llcsæsonen2026",
    },
    {
      title: "Absalon 4–2",
      cat: "kamp",
      year: "2026",
      date: "2026-05-10",
      opponent: "Absalons Boldklub af 2012",
      result: "4–2",
      excerpt: "Hjemme på Kunst 41. Seks mål, tre point i pulje B-3.",
      url: "https://www.instagram.com/larsbertocarlos/",
      tags: "#merekul",
    },
    {
      title: "Clean sheet, tre mål",
      cat: "kamp",
      year: "2026",
      date: "2026-06-14",
      opponent: "Stribberne",
      result: "3–0",
      motm: "Balthzer",
      excerpt: "Ti små larsbertoer sku’ til fodboldkamp. To måtte trække sig og to trådte til. Clean sheet, en GOAT assist. Balthzer hev den hjem.",
      url: "https://www.instagram.com/p/DZoncC3N8KH/",
      tags: "#chuchu",
    },
    {
      title: "Skurvognen 1–3",
      cat: "kamp",
      year: "2026",
      date: "2026-06-26",
      opponent: "Skurvognen FC",
      result: "3–1",
      excerpt: "Valby Kunst 40 inden sommerpausen. Tre mål på udebane. Skurvognen skrev det selv: 3–1 til @larsbertocarlos.",
      url: "https://www.instagram.com/skurvognen_fc/",
      tags: "#merekul",
    },
    {
      title: "Sidste minut, 3–2",
      cat: "kamp",
      year: "2024",
      date: "2024-06-01",
      opponent: "Valbyparken",
      result: "3–2",
      motm: "Jakob",
      excerpt: "Jakob to mål. Assists fra P, Louis og Anders. Magnus vinder-mål i de døende sekunder. Fem mål, tre point.",
      url: "https://www.instagram.com/p/C_ajrPDMP_O/",
      tags: "#llcsæsonen2024 #chuchu #merekul",
    },
    {
      title: "Lars vandt 3–1",
      cat: "kamp",
      year: "2024",
      date: "2024-05-14",
      opponent: "Hjemmebane",
      result: "3–1",
      motm: "Aske",
      excerpt: "God kamp. Aske MoM som sædvanlig. Fire mål og tre point. #ChuChu #MereKul",
      url: "https://www.instagram.com/p/C68Os3WspIB/",
      tags: "#ChuChu #MereKul",
    },
    {
      title: "Regndans, Celtic 3–1",
      cat: "historie",
      year: "2019",
      date: "2019-06-15",
      opponent: "Cph. Celtic",
      result: "3–1",
      motm: "Oskar",
      excerpt: "Dannebrogs 800 år. Oskar solo, Zeko på assist af OK, Abdi. Fire mål i regnen. MOTM: Oskar.",
      url: "https://www.instagram.com/p/ByvxyLtBFGR/",
      tags: "#merekul #chuchu #LLCsæsonen2019",
    },
  ],

  sponsors: [
    { name: "Bliv hovedsponsor", tier: "Hoved", blurb: "Logo på brystet og på forsiden. Skriv til os." },
    { name: "Banen", tier: "Guld", blurb: "Logo på ærmet og i kalenderen." },
    { name: "Vognen", tier: "Sølv", blurb: "Synlighed på web og i Award Show-programmet." },
    { name: "Skinne", tier: "Ven", blurb: "En kasse øl og et navn i årsskriftet. Det tæller." },
  ],

  shop: [
    { sku: "LLC-HOME-26", name: "Hjemmebane 25/26", price: "449 kr", tag: "Trøje" },
    { sku: "LLC-SCARF", name: "Halstørklæde", price: "179 kr", tag: "Merch" },
    { sku: "LLC-CAP", name: "Kasket", price: "149 kr", tag: "Merch" },
    { sku: "LLC-AWARD", name: "Award Show-plakat 2025", price: "89 kr", tag: "Print" },
  ],

  documents: [
    { title: "Vedtægter", date: "2024-03-12", file: "#", kind: "pdf" },
    { title: "Referat, generalforsamling 2025", date: "2025-03-18", file: "#", kind: "pdf" },
    { title: "Referat, bestyrelsesmøde maj 2026", date: "2026-05-06", file: "#", kind: "pdf" },
    { title: "Husorden, Valby Idrætspark", date: "2025-08-01", file: "#", kind: "pdf" },
    { title: "Trøje- og udstyrspolitik", date: "2025-07-20", file: "#", kind: "pdf" },
    { title: "Årsregnskab 2025", date: "2026-03-01", file: "#", kind: "pdf" },
  ],

  fines: [
    { player: "Jonas Lind", reason: "For sent til opvarmning", amount: 50, paid: false, date: "2026-08-10" },
    { player: "Alexander Pihl", reason: "Glemt indershirt", amount: 30, paid: true, date: "2026-08-10" },
    { player: "Emil Nørgaard", reason: "Gult kort, unødvendigt", amount: 40, paid: false, date: "2026-08-17" },
    { player: "Holdet", reason: "Tabt omklædning (fælles)", amount: 0, paid: true, date: "2026-08-17", note: "Pizza i stedet" },
    { player: "Marcus Høeg", reason: "Mobil på bænken", amount: 20, paid: false, date: "2026-08-24" },
  ],

  board: [
    {
      author: "Holdleder",
      date: "2026-08-24",
      title: "Kamp i aften — mødetid 19:10",
      body: "Kunst 7. Striberne er vasket. Tag sorte shorts og røde strømper. Boldpose hentes i containeren.",
    },
    {
      author: "Bestyrelsen",
      date: "2026-08-20",
      title: "Award Show 21. november",
      body: "Save the date. Nomineringer åbner 1. oktober. Tema: sort jakke, rødt slips — eller stribet trøje under jakken.",
    },
    {
      author: "Cheftræner",
      date: "2026-08-18",
      title: "Træning flyttet til torsdag",
      body: "Banen er optaget mandag. Torsdag 18:00, kunst 41. Besked er også lagt i Holdsport.",
    },
  ],
};
